on:
  push:
    branches:
      - master
  pull_request:

name: unit-tests

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.25.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run target
        run: go test -race -failfast -v ./...
